const HealthLibrary = {
  imaging_modalities: [
    "X-ray",
    "Ultrasound",
    "CT Scan (Computed Tomography)",
    "MRI (Magnetic Resonance Imaging)",
    "PET Scan (Positron Emission Tomography)",
    "Mammography",
    "Fluoroscopy",
    "Echocardiography",
    "Nuclear Medicine Imaging",
    "Angiography",
    "Interventional Radiology",
  ],
  imaging_body_regions: [
    "Head",
    "Brain",
    "Face",
    "Neck",
    "Throat",
    "Chest",
    "Lungs",
    "Heart",
    "Abdomen",
    "Liver",
    "Gallbladder",
    "Pancreas",
    "Spleen",
    "Stomach",
    "Kidneys",
    "Bladder",
    "Pelvis",
    "Uterus",
    "Ovaries",
    "Prostate",
    "Rectum",
    "Spine",
    "Back",
    "Bones",
    "Joints",
    "Shoulder",
    "Elbow",
    "Wrist",
    "Hand",
    "Leg",
    "Hip",
    "Knee",
    "Ankle",
    "Foot",
    "Blood Vessels",
    "Breast",
    "Eyes",
    "Ears",
    "Nose",
    "Sinuses",
    "Thyroid",
    "Muscles",
    "Skin (for superficial masses or lesions)",
  ],
  genders: ["Male", "Female"],
  weight_units: ["Kilogram (kg)", "Pounds (lbs)", "Tonnes (t)"],
  height_units: ["Centimeter (cm)", "Meter (m)", "Inches (inch)", "Feet"],
  medical_search_terms: [
    "hypertension",
    "diabetes",
    "mellitus",
    "asthma",
    "cardiovascular",
    "disease",
    "stroke",
    "breast",
    "cancer",
    "depression",
    "anxiety",
    "disorder",
    "tuberculosis",
    "COVID",
    "HIV",
    "AIDS",
    "malaria",
    "pneumonia",
    "arthritis",
    "chronic",
    "kidney",
    "obesity",
    "anemia",
    "hepatitis",
    "sickle cell",
    "mental",
    "health",
  ],
};

export default HealthLibrary;
